# Generated by Django 3.2.11 on 2022-10-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='slug_field',
            new_name='slug',
        ),
    ]
